### PR TITLE
window and linux support

### PR DESCRIPTION
**Pull request by nsmgr8**
Adds linux support by using libnotify. That is, only the linux desktops that have `notify-send` command can use this utility.

Also adds windows 10 support using win10toast.

### CODE REVIEW

**Comment by s1s1ty** [comment]
Well, Thanks for your contribution. But first of all, resolve conflict and also write instruction how to install on the readme. Secondly, send marge request on v2 branch. 👍

**Comment by nsmgr8** [comment]
There's no resolve conflict. It's on master branch. I do not understand your v1, v2 branch policy. I have never seen such thing. You can merge this on master and then put it back on your v2 or make v3 or vn or whatever. There should be only one development branch, not multiple moving branches.

Also, there's no different thing to do to install. I have updated the setup.py. It will know which platform it is installing in and install the right packages. So the current installation method `pip install` just works!

**Comment by s1s1ty** [comment]
I appreciate you. I've changed my plan from package system to script system. Master branch is related to package system. Yeah, I need to call development branch instead of v2 branch and I also forgot to mention about contributing process.  Please send me PR on my development branch. Thanks

**Comment by s1s1ty** [comment]
I appreciate you. Yeah,  I need to mention contributing process and also make branch name development instead of v1. Would you please send PR again on development branch?

**Pull request merged**
